### ISSUE TITLE
Finale Tanks not spawning at the same spot

### ISSUE THREAD

**Issue by SirPlease** [SirPlease/ZoneMod#10]
As title indicates, teams tend to get their Finale tanks at different locations.
Can we force them to spawn at the exact same spot?

Sidenote: Losing team can have a large advantage by knowing where the Tank will spawn in the finale, but on the other hand it's rather unpredictable where the Director will spawn these Tanks and if they will be in favor for a certain team.

**Comment by LuckyServ** [comment]
If you want to make both tanks spawn in the exact same location for both teams, then both teams should know the location before it spawns. It should also spawn in a safe location, so you would need to handpick possible spawn locations for every finale (let's not forget custom maps too).
