### ISSUE TITLE
Stripper config doesn't load for Blood Harvest depending on map name capitalization

### ISSUE THREAD

**Issue by devilesk** [SirPlease/ZoneMod#18]
Since blood harvest appears to be the only default campaign that uses capitalized map names and the filenames for the stripper configs are case sensitive, the stripper configs won't be applied if you switch to a Blood Harvest map by using a lowercase map name.

For example, `!map c12m1_hilltop` won't load the stripper config `C12m1_hilltop.cfg`, but `!map C12m1_hilltop` will load it. Choosing a map via the admin menu has this issue because the map names are all lowercase in the menu, unless you have a maplist file with the correct map name capitalization for Blood Harvest.

The workaround I'm using is just creating a copy of the Blood Harvest stripper configs but with all lowercase filenames.

**Comment by devilesk** [comment]
Another issue related to capitalization of the Blood Harvest maps is this line defined in shared_settings.cfg never gets applied if you're playing through the campaign:
https://github.com/SirPlease/ZoneMod/blob/6428e619cebe9b525ce0660a2a655e3e9d62e556/cfg/cfgogl/zonemod/shared_settings.cfg#L345

Adding `tank_map_flow_and_second_event C12m5_cornfield` with capital C should fix it.

**Comment by SirPlease** [comment]
I've fixed both of these issues by forcing the maps to load in lowercase (I didn't bother with Scavenge, but it's not hard to do so) with [this](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/bloodharvestfix.vpk)

I've renamed the stripper files to all be lowercase as well.
Thanks for reporting! 👍
