### ISSUE TITLE
Diescraper map 2 medkit spawns

### ISSUE THREAD

**Issue by devilesk** [SirPlease/ZoneMod#19]
We found a medkit spawn on map 2 of Diescraper https://clips.twitch.tv/PrettyMoralPheasantDancingBaby

I did some testing and found there's two `weapon_item_spawn` in that area `"hammerid" "432636"` and `"hammerid" "633746"` with medkits enabled `"item2" "1"`

I added a couple stripper rules to `l4d2_diescraper2_streets_361.cfg` to disable the medkit flag:
```
; --- Prevent medkit spawn
modify:
{
	match:
	{
		"hammerid" "432636"
	}
	replace:
	{
		"item2" "0"
	}
}
{
	match:
	{
		"hammerid" "633746"
	}
	replace:
	{
		"item2" "0"
	}
}
```

**Comment by SirPlease** [comment]
Fixed @ [L4D2 Competitive Rework](https://github.com/SirPlease/L4D2-Competitive-Rework)
Thanks for the report and fix (:
