### ISSUE TITLE
Diescraper map 4 inconsistent saferoom weapon spawn

### ISSUE THREAD

**Issue by devilesk** [SirPlease/ZoneMod#21]
You can get double shotgun and no smg in the saferoom.

To fix it and make sure there's always smg+shotgun, I added the following to `l4d2_diescraper4_top_361.cfg`
```
modify:
{
	match:
	{
		"hammerid" "625294"
	}
	replace:
	{
		"weapon_selection" "any_smg"
	}
}
```
This entity was previously a tier1_any weapon_spawn.

**Comment by SirPlease** [comment]
Fixed @ [L4D2 Competitive Rework](https://github.com/SirPlease/L4D2-Competitive-Rework)
Thanks for the report and fix (:
