### ISSUE TITLE
Missing mapinfo for Diescraper maps

### ISSUE THREAD

**Issue by devilesk** [SirPlease/ZoneMod#22]
I noticed the line `[confoglcompmod.smx] [MI] MapInfo for l4d2_diescraper1_apartment_361 is missing.` in my logs. It looks like the mapinfo.txt is using Diescraper v3.3 map names instead of v3.61. I don't know if any of the coordinate values have changed since v3.3 and would also need to be updated.

I did a search to list all the affected files and saferoominfo.txt and l4d2lib/mapinfo.txt have the same issue as well.
```
./cfg/cfgogl/zm1v1/mapinfo.txt:1380:	"l4d2_diescraper1_apartment_33"
./cfg/cfgogl/zm3v3/mapinfo.txt:1383:	"l4d2_diescraper1_apartment_33"
./cfg/cfgogl/zm2v2/mapinfo.txt:1383:	"l4d2_diescraper1_apartment_33"
./cfg/cfgogl/zonemod/mapinfo.txt:1389:	"l4d2_diescraper1_apartment_33"
./addons/sourcemod/configs/l4d2lib/mapinfo.txt:1332:    "l4d2_diescraper1_apartment_33"
./addons/sourcemod/configs/saferoominfo.txt:672:	"l4d2_diescraper1_apartment_33"
./ConfigUpdates/Zonemod-1.9.3/cfg/cfgogl/zm1v1/mapinfo.txt:1380:	"l4d2_diescraper1_apartment_33"
./ConfigUpdates/Zonemod-1.9.3/cfg/cfgogl/zm3v3/mapinfo.txt:1383:	"l4d2_diescraper1_apartment_33"
./ConfigUpdates/Zonemod-1.9.3/cfg/cfgogl/zm2v2/mapinfo.txt:1383:	"l4d2_diescraper1_apartment_33"
./ConfigUpdates/Zonemod-1.9.3/cfg/cfgogl/zonemod/mapinfo.txt:1387:	"l4d2_diescraper1_apartment_33"
```

**Comment by SirPlease** [comment]
Fixed over at [L4D2 Competitive Rework](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/cc72695c0fa5a48ae05df93f990947873bba70c3)
