### ISSUE TITLE
Enable ZoneMod [Help]

### ISSUE THREAD

**Issue by Berndinox** [SirPlease/ZoneMod#6]
Hy,

i'm new to Steamapps and got a question about how to enable ZoneMod with its default Settings.

I've added:

```
exec cfgogl/zonemod/confogl.cfg
exec cfgogl/zonemod/confogl_plugins.cfg
```
to my Server1.cfg in /cfg.

`rcon sm plugins list` shows more then 100 plugins loaded, so that should be fine.

Do i miss anything, or is this everything?
Anything else i have to do when connected to my server in game?

BR Bernd

**EDIT:**
I've changed the order to:
```
exec cfgogl/zonemod/confogl_plugins.cfg
exec cfgogl/zonemod/confogl.cfg

```
Seems logical to first load the plugins, then apply settings?!

I've also added: `confogl_setcvars` at the end of the server conf.
however i'm not really sure how the cvars mechanism is working, some options are not set, but i can change them directly on the command line withoud `confogl_addcvar`.

**Comment by Berndinox** [comment]
Ok..
Loading via "!match" is working fine after removing the both exec commands from the server$NUM.cfg
Seems autoloading is breaking things..

-> Close

BR

**Comment by SirPlease** [comment]
If you only wish to have Zonemod loaded at all times, you can just include "sm_forcematch zonemod" to your server.cfg, that'll do the trick.  
I'll close this for now, feel free to re-open if you have follow up questions.
