### ISSUE TITLE
1.9.3 l4d_boss_percent.smx has performance problem

### ISSUE THREAD

**Issue by moooonk** [SirPlease/ZoneMod#7]
hi SirPlease.
With My test. update 1.9.3 l4d_boss_percent.smx, use too many CPU resources.
2 player in server,  srcds will use 100% CPU resources. You know srcds can only use one CPU core.It will make server so lag.
Replace l4d_boss_percent.smx with old version, no such problem.
Hope can fix it.

**Comment by SirPlease** [comment]
Thanks for the report monk, the new version includes support for the Dark Carnival: Remix campaign but it requires a crappy workaround. 

I've optimized the workaround now [#3dfc52c3fade1fe40af6ae91233c793663c04cce](https://github.com/SirPlease/ZoneMod/commit/2cb207a74cd5530af1c5bdc1c5dfee902aec2169)
Feel free to re-open the issue if it persists.
