### ISSUE TITLE
Friendly fire should reduce damage bonus.

### ISSUE THREAD

**Issue by LuckyServ** [SirPlease/ZoneMod#8]
When a survivor friendly fires another one on temporary HP, the damage bonus stays the same when it should reduce it.

**Comment by SirPlease** [comment]
Not entirely true.
The system worked fine with damage dealt by non-shotgun weapons, the issue arose when we started modifying the maximum amount of FF Shotguns could deal.

This however uses SDKHooks_TakeDamage, which will end up being ignored by the methods we use to capture damage taken (SDKHooks_OnTakeDamage and SDKHooks_OnTakeDamagePost)

Issue is resolved in [last commit](https://github.com/SirPlease/ZoneMod/commit/8fefac871ec4d0af688bffa8abd5f9a3c1b7e64b)

Thanks for reporting!
